### ISSUE TITLE
Please upgrade to pdfmake version to 0.1.54 otherwise can not use on mobile

### ISSUE THREAD

**Issue by dancomanlive** [Lugriz/pdfmake-wrapper#1]
See https://github.com/bpampuch/pdfmake/issues/1664

**Comment by ZaLiTHkA** [comment]
@dancomanlive, `pdfmake-wrapper` defines it's dependency as `"pdfmake": "^0.1.40"`, so if you remove and reinstall `pdfmake-wrapper`, it will install with `pdfmake@0.1.58` (current version at time of writing)..

**Comment by Lugriz** [comment]
New release is ready!
