### ISSUE TITLE
When I can break a new page ?

### ISSUE THREAD

**Issue by Paul75** [Lugriz/pdfmake-wrapper#14]
Hello,

I must create PDF with pages and in my code I want add NewPage like : $pdf->addPage() and that create page new.

When I can di this ? simple ?

Because I must create a document with about more than 35 pages.

Thanks

**Comment by Ng-India99** [comment]
hey Did you find the solution ??

**Comment by Paul75** [comment]
Hello

No....

Thanks

**Comment by Ng-India99** [comment]
hi,

we can break the page by below condition,

  pdf.add(new Txt(`/n`).pageBreak("after").end);

**Comment by Paul75** [comment]
Hello,

It works. I test for one PDF export and works.

Thanks
