### ISSUE TITLE
size of QRCODE

### ISSUE THREAD

**Issue by Paul75** [Lugriz/pdfmake-wrapper#16]
Helllo,

For QrCode I do : 
```
new QR('MY DATA...')
          .fit(42)
          .margin(0)
          .width('auto')
          .alignment('right').end
```
I I di fit with 42 it big and if I do fit with 41 is verry small....

make 41.5 not works.

When I can give a with ?

**Comment by Lugriz** [comment]
Hi!
I think the problem is that you are using width() and fit() at the same time. Try using one of them.
