### ISSUE TITLE
Is this module works in server side ?

### ISSUE THREAD

**Issue by sudu99** [Lugriz/pdfmake-wrapper#18]
I tried to implement this on my AWS lambda (typescript) ...I am getting following error. plz advice. thanks

MY CODE:
import { PdfFormEvent } from './model';
import { ApiService } from '@coral-eforms/api-service';
// import * as fs from 'fs';
// import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';
import { PdfMakeWrapper } from 'pdfmake-wrapper';

export class GenFormPdfHandler {

  constructor(private apiService: ApiService) {
    // console.log('HELLO');
  }
public async handle(event: PdfFormEvent) {

PdfMakeWrapper.setFonts(pdfFonts);
    const pdf = new PdfMakeWrapper();
    pdf.pageSize('A4');
    pdf.styles({
      orgName: {
        fontSize: 20,
        bold: true,
        alignment:'right',
        margin:[0,30,0,0]
      },
      formTitle: {
        fontSize: 20,
        bold: true,
        alignment:'left',
        margin:[0,40,0,5],
      },
      userSubmission: {
        alignment:'left'

      },
      fieldTitle: {
        margin: [0,15,0,0],
        bold: true
      },
      fieldValue: {
        alignment:'left',
        margin: [0,15,0,0]
      },
      fieldSignature: {
        // fit: [100, 100],
        margin: [0,5,0,0],
        alignment:'left'
      },
      center: {
        alignment:'center',
      },
    });
    pdf.defaultStyle({
      // columnGap?: 10,
      color: '#3a4045'
    });
    pdf.add('Hello world!');

    pdf.create().download('file.pdf');
}

ERROR:
(node:46868) UnhandledPromiseRejectionWarning: /Users/studiptaprodhan/coral-eforms/src/functions/generateFormPdf/node_modules/pdfmake-wrapper/index.js:1
export * from './lib/pdfmake-wrapper';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/studiptaprodhan/coral-eforms/src/functions/generateFormPdf/generateFormPdf.handler.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (/Users/studiptaprodhan/coral-eforms/node_modules/ts-node/src/index.ts:839:23)
(node:46868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Lugriz** [comment]
It does not work on server side, but it will in the next release.

**Comment by Leccho** [comment]
And when is the next version comming up ?

**Comment by Lugriz** [comment]
@Leccho Now the library support server side development.
[https://github.com/Lugriz/pdfmake-wrapper#working-on-server-side](https://github.com/Lugriz/pdfmake-wrapper#working-on-server-side).

**Comment by Leccho** [comment]
@Lugriz Nice!
