### ISSUE TITLE
PDF download file name from DataUrl

### ISSUE THREAD

**Issue by silvermind20** [Lugriz/pdfmake-wrapper#19]
First, I want to thank you for the awesome wrapper you have provided. I have a small issue that I couldn't find answer for it anywhere else, so hoping you can help me. In an Angular project, I am creating different PDF files and set the title of each of them this way:
` pdf.info({ title: 'My Report' + date });`
and I am showing the pdf using this:
`pdf.create().getDataUrl((dataURL: any) => {
    this.pdfSource = this.sanitizer.bypassSecurityTrustResourceUrl(dataURL);
    });`
in a div like this:
`<div class="pdf"><object class="pdfViewer" [attr.data]="pdfSource" type="application/pdf"></object></div>`
It is all good up to here and I can see my title is shown up top. But when I click on the download icon inside the PDF viewer which downloads the file, it opens the "Save As" window and shows the file name as "download.pdf". Is there anyway that I can force my title into that and it would automatically show "My Report 05-20-2020.pdf" that I set from pdf.info() or any other method that takes care of it?
Much appreciated!

**Comment by Lugriz** [comment]
Hi @silvermind20 !
Thanks for using Pdfmake-wrapper, you could use the download method, this method allows you to set the name of the downloaded file.
`
pdf.create().downdoad('myCustomName.pdf');
`
You can see the available methods [here](https://github.com/Lugriz/pdfmake-wrapper#icreatepdf).
