### ISSUE TITLE
Convert html to pdf

### ISSUE THREAD

**Issue by KelvinNjihia** [Lugriz/pdfmake-wrapper#2]
I have an angular app. In this I want to convert the webpage to pdf. Using class/div slection.

Is this possible with pdfmake-wrapper?

**Comment by AmbroiseVuaridel** [comment]
+1

**Comment by Lugriz** [comment]
@KelvinNjihia Hi!

You can use [html2canvas](https://html2canvas.hertzen.com/) for transforming the HTML in an image, then you can transform the canvas content in a dataurl (base64) and pass it to the Img object from pdfmake-wrapper, like this: new Img(canvasResult).build(). I hope to add a feature like that. (The package is open for pull request and contributors)

Thanks for using pdfmake-wrapper!

**Comment by KelvinNjihia** [comment]
Thank you very much @Lugriz !
Just a follow up question. How would I do this case: This is the component.html

`<div class="reports-table" #content id="print-section">
<h2>Heading</h2>
<p> My content. Here we go.</p>
</div>

<div class="footer-share" (click)="print()">
          <button class="btn btn-back"><span class="mdi mdi-printer"></span><span>&nbsp;Print</span></button>
        </div>
`
How should I write my `print()` function?

**Comment by KelvinNjihia** [comment]
I guess I was able to fix it!!

Thanks @Lugriz !!!

Just a follow up question how can I set Image attributes like height and width? usinf pdfmake-wrapper?

**Comment by Lugriz** [comment]
@KelvinNjihia please, can you share your solution? for the community.

About your next question, all the definitions extends of [StyleDefinition](https://github.com/Lugriz/pdfmake-wrapper/blob/master/src/lib/definitions/style-definition.ts) you can check the methods it has. you can try to use either **width(number)** and **height(number)** methods or  the **[fit([number, number])](https://github.com/Lugriz/pdfmake-wrapper/blob/master/src/lib/definitions/image.ts#L35)** method of the **Img** object.

for any question outside of this topic (Convert html to pdf) please, refer it as a new issue.

**Comment by KelvinNjihia** [comment]
So this is my solution:
I hope it get's to help someone: Here is the html component

```
<div class="reports-table" #content id="print-section">
<h2>Heading</h2>
<p> My content. Here we go.</p>
</div>

<div class="footer-share" (click)="print()">
          <button class="btn btn-back"><span class="mdi mdi-printer"></span><span>&nbsp;Print</span></button>
        </div>
```

And how I went about writing my function.

```
async generatePDF() {


    html2canvas(document.querySelector("#print-section")).then(async canvas => {

      var imgWidth = 208;
      var pageHeight = 295;
      var imgHeight = canvas.height * imgWidth / canvas.width;
      var heightLeft = imgHeight;
      const canvasResult = canvas.toDataURL("image/png");
      document.body.appendChild(canvas)
      // console.log(canvasResult);

      const pdf: PdfMakeWrapper = new PdfMakeWrapper();

      pdf.add( new Txt('Tmp Verwaltungs GmbH - Stundennachweis').alignment('left').fontSize(15).bold().end);

      pdf.add( await new Img('/assets/images/tmp-logo.png').fit([100, 70]).alignment('right').margin([0, 20]).build());

     pdf.add( await new Img(canvasResult).fit([628, 800]).margin([0, 0, 20, 0]).build());
     pdf.pageSize('A4');
     pdf.pageMargins([ 40, 60, 40, 60 ]);
     pdf.info({
      title: 'Tempton - Stundennachweis',
  });
     // pdf.pageOrientation('landscape');

    pdf.create().print();
    });

  }
```

PS:
When using this method, be careful as sometimes the images are zoomed out. Also I did not figure out how to use %age for the width other than using px.

More ideas are welcome.
