### ISSUE TITLE
I failed to see how to combine different style

### ISSUE THREAD

**Issue by Leccho** [Lugriz/pdfmake-wrapper#20]
How do you write:
This is _an example_ please **HELP ME**!

**Comment by Lugriz** [comment]
@Leccho You need to divide the text in fragments, for example:
```javascript
new Txt([
   'This is ',
   new Txt('an example').italics().end,
   ' please ',
   new Txt('HELP ME!').bold().end
]).end
```

**Comment by Leccho** [comment]
Thanks, good to know.

**Comment by AurelienFT** [comment]
This should be added to documentation.

**Comment by Lugriz** [comment]
@AurelienFT We are working to improve the documentation.
