### ISSUE TITLE
lineHeight Style not available.

### ISSUE THREAD

**Issue by wilberpal** [Lugriz/pdfmake-wrapper#22]
Hello,

I'm trying to use the style lineHeight to increase the space between lines but it looks like it's not included?

is there any other way to achieve this: I need something like this

Pdfmake code:
var dd = {
	content: [
		{
		    **lineHeight**: 2,
		    text:'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines. Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines.'
		}
	]
}

Thanks.

**Comment by Lugriz** [comment]
Hi @wilberpal! Can you try to use something like this:

`
const pdf = new PdfmakeWrapper();

pdf.styles({
  myCustomStyle: {
      lineHeight: 2
  }
});

pdf.add(
   new Txt('any text').style('myCustomStyle').end
);
`
