### ISSUE TITLE
How to start translating documentation into Spanish?

### ISSUE THREAD

**Issue by rpalaciosg** [Lugriz/pdfmake-wrapper#34]
Hi Luis 👋, I come from Manuel Zapata's channel. Congratulations for pdfmake-wrapper a great job 💯.
In the video you mentioned that we can collaborate by translating the documentation into Spanish.

What would be the way to do it❓, I would like to help.

**Comment by Lugriz** [comment]
Hi @rpalaciosg! 

Thanks for you interest to contribute in this library. First of all you need to **fork** the repository, after that you need to follow the steps in this [contributing.md](https://github.com/Lugriz/pdfmake-wrapper/blob/master/CONTRIBUTING.md) file. If you have any question please, feel free to follow the discussion in [contributing](https://github.com/Lugriz/pdfmake-wrapper/discussions/categories/contributing) discussion section creating a new one based on this topic. We can land it there!

**Comment by rpalaciosg** [comment]
Muchas gracias Luis, lo voy hacer.

Hay algo que quiero comentarte, y me disculpó si elegí el canal incorrecto para hacerlo. Soy parte de una comunidad que apenas empieza 'Javascript Ecuador' orientada al open source, y estamos preparando una especie de desconferencia(son tipo charlas o workshops de forma más informal) para el mes de Junio.

Quisiera invitarte y preguntarte si estarías interesado en dar una charla o workshop en español sobre el desarrollo y uso de esta librería pdfmaker-wrapper? Yo pienso que sería un feed grande, porque en mi país está en auge la creación de sistemas de facturación donde se necesita mucho la generación de pdfs, el javascript y typescript está creciendo en popularidad y al ya tener soporte para el servidor creo que estaría genial un workshop de eso.  Creo también que podrías conseguir más interesados a colaborar en el desarrollo de la librería incluso la traducción de la documentación.

Sin más agradezco mucho tu respuesta, espera mi PR pronto, y si tienes alguna duda porfavor házmela saber ya sea por aquí o por twitter @rpalaciosg_ además te dejo una invitación al grupo en Telegram de la comunidad https://t.me/javascriptecuador.

Un saludo.
