### ISSUE TITLE
Two texts in the same line.

### ISSUE THREAD

**Issue by PabloASua** [Lugriz/pdfmake-wrapper#64]
Hi there!
Please, could you tell me how can I place two texts in the same line with different characteristics like bold or font size?

Something like:  **First text in bold type** and, in the same line, _Second text in italic type_.

Greate library!

Thank you.
Regards,

**Comment by Lugriz** [comment]
Hi @PabloASua!

This issue is duplicated and it's already solved: https://github.com/Lugriz/pdfmake-wrapper/issues/20
