### ISSUE TITLE
Two texts with diferent style in the same line

### ISSUE THREAD

**Issue by PabloASua** [Lugriz/pdfmake-wrapper#65]
Hi there, please, could you tell me how can I place two text strings with different styles (like bold, color, etc.) in the same line?
I couldn't find the way.

Regards

**Comment by Lugriz** [comment]
Hi @PabloASua!

This isssue is duplicated, I already answer your issue [here](https://github.com/Lugriz/pdfmake-wrapper/issues/64), this was already resolved here: https://github.com/Lugriz/pdfmake-wrapper/issues/20

Please, close this issue if this works for you.

**Comment by PabloASua** [comment]
Thanks!
